### PR TITLE
Update ru_RU.lang

### PR DESCRIPTION
**Pull request by Xottab-DUTY**

### CODE REVIEW

**Comment by defiler** [comment]
Специалист по избиванию деревьев - зачёт)))

**Comment by Xottab-DUTY** [comment]
Угу) Treepuncher))

**Comment by Xottab-DUTY** [comment]
@BluSunrize what can you say about this pull request? Will you pull this?)

**Comment by BluSunrize** [comment]
Yeah, I will =P

**Comment by Xottab-DUTY** [comment]
Thanks! =)
Now the mod has real Professional Treepuncher, not Proffesional lumberjack =P

**Comment by BluSunrize** [comment]
Ah, so that's the difference. I can't read it, so... =P

**Comment by Xottab-DUTY** [comment]
Yeah, but not only that =)

**Pull request merged**
